name: PlayerCoords
main: skyss0fly\PlayerCoords\Main
version: 1.5.0
api: 6.0.0
author: skyss0fly
description: Shows your coordinates or broadcasts them.
commands:
  coords:
    description: Show your exact coordinates
    permission: PlayerCoords.coords
  fcoords:
    description: Show your floored coordinates
    permission: PlayerCoords.fcoords
  bccoords:
    description: Broadcast your coordinates
    permission: PlayerCoords.bccoords
permissions:
  PlayerCoords.coords:
    default: true
  PlayerCoords.fcoords:
    default: true
  PlayerCoords.bccoords:
    default: op
